### ISSUE TITLE
Files app integration doesn't update properly

### ISSUE THREAD

**Issue by kra-mo** [meganz/iOS#115]
## General Information

* MEGA Version: 14.5 (2405211457)

* iOS Version(s): 17.5.1

* Reproducible? (Yes/No): Yes

##  What happened?

When a file is updated remotely, the version of it shown in the Files app doesn't update accordingly. This is even after opening the file inside of the MEGA app, where it does show the correct, updated version.

## What did you expect to happen?

The file is updated to the correct version, preferably automatically via a background task, but at least when opening it from the Files app. (In the worst case, only when opening it from MEGA, but not having to enter the app would be ideal.)

See: https://github.com/keepassium/KeePassium/issues/369

**Comment by jx-mega** [comment]
The issue should not be occurring in our latest versions, could you please update the app to v16.2 and try again?

**Comment by jx-mega** [comment]
Hello,

Thank you very much for your feedback.

We could reproduce such behaviour and we have passed it to our team for a fix.

Have a MEGA-awesome day and contact us should you need any other assistance.

**Comment by jnavarrom** [comment]
Hello @kra-mo,

The problem you are reporting is the following one, right?

https://github.com/user-attachments/assets/7e256406-4bc0-4564-8ba0-f88de5daea88

Thanks for reporting.

**Comment by kra-mo** [comment]
Yes, that is the issue.

**Comment by jnavarrom** [comment]
Thanks for the quick response. 
I tried edit a file with another app (opening the file from Files -> MEGA) and it seems it worked as expected, despite there is another different problem (the file does not exist, need investigate this further)


https://github.com/user-attachments/assets/44c4b158-f942-44cf-9037-7f699dc5cf4c

**Comment by kra-mo** [comment]
Sorry, by outside the MEGA app, I meant remotely and then waoting for the app to sync.

**Comment by jnavarrom** [comment]
Do you mean modifying the file remotely from another client? for example MEGA desktop app?

**Comment by kra-mo** [comment]
Yes.

**Comment by jnavarrom** [comment]
This issue should be fixed in version 16.5, can you please give it a try?

Thanks

**Comment by kra-mo** [comment]
It does work, yes. Thanks.
