### ISSUE TITLE
[Feature Request] Support JPEG-XL and AVIF

### ISSUE THREAD

**Issue by mshibanami** [meganz/iOS#118]
## General Information

* MEGA Version: 16.0.1
* iOS Version(s): iOS 18.0.1
* Devices/Simulators: iPhone 15
* Reproducible? (Yes/No): Yes

## What happened?

Currently, the iOS app doesn't recognize JPEG-XL (`.jxl`) and AVIF (`.avif`) files as images. Is there a chance to add support for them? I believe that at least JPEG-XL makes sense to support since [it's now supported by the iPhone 16 Pro](https://www.macrumors.com/2024/09/09/iphone-16-pro-supports-jpeg-xl-format/).

FWIW, this is my personal implementation: https://github.com/mshibanami/meganz-iOS/commit/0836fdc38f76413f13f826877bc58bdc399c3197

I confirmed that it works fine for me. (= `UIImageView` already supports both formats.)

(I won't create a pull request since the team always seems to prefer making changes internally, and I accidentally included an unnecessary change.)

## What did you expect to happen?

Image files with `.jxl` or `.avif` extensions should be recognized as images, and I should be able to preview them with horizontal swipes.

## Misc.

IIRC, my changes are not enough as they don't organize the items in the Recents section properly. Also, these formats aren't recognized on the Web either. Therefore, I think changes will be needed for https://github.com/meganz/sdk as well.

---

Thank you for maintaining this great service!

**Comment by jnavarrom** [comment]
Hello,

Both images type are now supported in versions 16.2+

Thanks for reporting

**Comment by mshibanami** [comment]
Perfect. It works for me now. Thank you for the quick work!
