### ISSUE TITLE
add background refresh feature

### ISSUE THREAD

**Issue by noproxy** [meganz/iOS#26]
The MEGA iOS app only support download files in the foreground. If put MEGA app to background, it will be suspend and the downloading is paused. So I have to set my iPhone never turn off screen and keep MEGA foreground to download somethings. This causes terrible user experience.

I notice that iOS 7+ supports executing Background App Refresh.  I think MEGA can add background  refresh to download or sync in the background.

**Comment by jnavarrom** [comment]
Hi,

You are right. It is a pending issue (we are focus on others features).

We will work on it in the future. Sorry for the inconvenience but I can't give you an ETA for this issue.

**Comment by sofqi** [comment]
This seems to work for me in iOS 10
