### ISSUE TITLE
Feature Request: Full Files app integration

### ISSUE THREAD

**Issue by sirredbeard** [meganz/iOS#34]
Currently accessing Mega files from Apple's iOS Files app gives access to Mega files, but only through a custom and limited interface.

This interface is not as easy to use as the default iOS Files app interface and it lacks some functionality, like markup options, that the default iOS Files app interface contains.

I would like to request that Mega fully support iOS Files app integration, a la OneDrive, Dropbox, etc.

If this is not possible due to Mega's encryption, then I would like to request an interface that is made to resemble the default iOS Files app interface with, if possible, markup options.

Thank you.

**Comment by tingspain** [comment]
Hello, Any news about this feature? I am new on the iOS world, but I dont mind to help

**Comment by LeonardoMantovani** [comment]
3 years passed... Any news about this feature?
I'm choosing a new cloud storage a this is the only thing preventing me from switching to Mega

**Comment by tingspain** [comment]
@LeonardoMantovani I have been waiting for 3 years too but nothing yet. A lot new features have been added but for me, IMHO, no very relevant or useful features like the chat one. :-/

**Comment by floam** [comment]
How about a File Provider extension on macOS?
