### ISSUE TITLE
The project is not building in cause of the "Command PhaseScriptExecution failed with a nonzero exit code" 

### ISSUE THREAD

**Issue by darkForestCat** [meganz/iOS#39]
Hello, I am using the latest version of iOS, Xcode 10.3 and the current version of MEGA, using Mac OS Mojave.
I did everything like it was in the instruction but I get this type of error when I try to build the project on the simulator or my device:

`/Users/dkforestcat/Library/Developer/Xcode/DerivedData/iMEGA-aucaqadrtuyglgcucfsfowgcuqym/Build/Intermediates.noindex/Karere.build/Debug-iphoneos/Karere.build/Script-A838B2231E96860900875D96.sh: line 3: cmake: command not found
Command PhaseScriptExecution failed with a nonzero exit code`

**Comment by darkForestCat** [comment]
@jnavarrom can you help me please?

**Comment by jnavarrom** [comment]
Hi @darkForestCat,

Do you have installed `cmake` in your system?

**Comment by darkForestCat** [comment]
@jnavarrom no, I did not.

**Comment by darkForestCat** [comment]
I need to do it?

**Comment by jnavarrom** [comment]
There is a run script in Karere project to generate the chat bbdd scheme:

```cd ../../src
cmake -P genDbSchema.cmake```

> cmake: command not found 

Please install it (using homebrew for example or other) and let me know if it works.

**Comment by darkForestCat** [comment]
@jnavarrom oh, okay I will try it and let you know!

**Comment by jnavarrom** [comment]
@darkForestCat did you manage the issue?

**Comment by darkForestCat** [comment]
@jnavarrom yes, excuse me for the long time I had a lot of work to do, so I have installed cmake, using homebrew, but now I get another type of the error: `error: Build input file cannot be found: '/Users/dkforestcat/ios/iMEGA/Vendor/Karere/src/karereDbSchema.cpp'`

**Comment by darkForestCat** [comment]
Just now cleaned everything and restarted.Everything works.Thanks you a lot for your help!
