### ISSUE TITLE
Maybe enable bitcode in the prebuilt 3rd Party libraries?

### ISSUE THREAD

**Issue by mattw-mattw** [meganz/iOS#40]
when trying to build with my actual iPhone as the target:

Showing Recent Messages
:-1: '/Users/admin/Desktop/just-exploring-3/SDK/bindings/ios/3rdparty/lib/librtc_sdk_objc.a(rand_extra.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

## General Information

* MEGA Version:
latest

* iOS Version(s):
12.1

* Devices/Simulators:
iPhone 7

* Reproducible? (Yes/No):
Yes

##  What happened?
link error per above

**Comment by jnavarrom** [comment]
WebRTC updated, please can you try again?

**Comment by jnavarrom** [comment]
Bitcode is deprecated with Xcode 14: https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-14-release-notes
