### ISSUE TITLE
No Video shown on video calling

### ISSUE THREAD

**Issue by paolorevillosa** [meganz/iOS#41]
## General Information

* MEGA Version:
latest
* iOS Version(s):
13
* Devices/Simulators:

* Reproducible? (Yes/No):
Yes

##  What happened?
So im using Mega app for ios for video calling. (cause i dont want to use some shitty apps that will migth take my data). But after i update the my ios to 13. I cant shared my video to whom im i talking

## What did you expect to happen?
Should share video on both end devices

**Comment by jnavarrom** [comment]
Hi @paolorevillosa ,

It is a known bug. We have a version (4.5) in TestFlight that fixes the issue. 
We will send the version to the App Store (but we haven't an ETA for this version). 
You can install this version becoming a member of our TestFlight program [MEGA TestFlight](https://testflight.apple.com/join/4x1P5Tnx).

Regards

**Comment by paolorevillosa** [comment]
Thanks i think im gonna wait for the update

**Comment by jnavarrom** [comment]
Fixed in release https://github.com/meganz/iOS/releases/tag/4.8.5
