### ISSUE TITLE
Building for iOS Simulator, but the linked library 'libcryptopp.a' was built for iOS.

### ISSUE THREAD

**Issue by Xcdmau5** [meganz/iOS#43]
## General Information

I'm trying to build app in iOS Simulator after updating Xcode to Version 11.4 (11E146).  Get "Building for iOS Simulator, but the linked library 'libcryptopp.a' was built for iOS." error when building for Simulator. For iOS Devices everything is ok. I downloaded prebuild 3dparty libs from your source.

* iOS Version(s):
 iOS 13.4
* Devices/Simulators:
Simulator iOS 13.4

* Reproducible? (Yes/No):
Yes

**Comment by jnavarrom** [comment]
It fails indeed. Really weird that it doesn't work on Xcode 11.4, the library was build for simulator and on previous Xcode versions it worked well

> lipo -info libcryptopp.a 
> Architectures in the fat file: libcryptopp.a are: armv7 armv7s x86_64 arm64 

<img width="535" alt="Screenshot 2020-03-26 at 16 10 14" src="https://user-images.githubusercontent.com/3861964/77662673-7521d200-6f7c-11ea-885d-4afb7b3ed790.png">

**Comment by jnavarrom** [comment]
You need rebuild `cryptopp`, remove the lib (lib/libcryptopp.a) and headers (include/cryptopp) and run the cryptopp script (build-cryptopp.sh)

<img width="964" alt="Screenshot 2020-03-26 at 16 26 21" src="https://user-images.githubusercontent.com/3861964/77664433-8e2b8280-6f7e-11ea-8bb5-c1bcd3b26adf.png">

**Comment by Xcdmau5** [comment]
I rebuild cryptopp for devices and simulator and now have Undefined symbol errors. Maybe it's better if you will upload new building lib for downloading from storage?

<img width="630" alt="Screenshot 2020-03-26 at 17 41 19" src="https://user-images.githubusercontent.com/26894470/77672551-54ac4480-6f89-11ea-9958-d5a7c48cc377.png">

**Comment by jnavarrom** [comment]
What is Clouds(Combine)?

**Comment by jnavarrom** [comment]
cryptopp Xcode_11.4
https://mega.nz/#!oQMkHA5A!vVowBV_nh7hWEDptDOkYk_G2nME6NtmlZju5khCvhXc

**Comment by Xcdmau5** [comment]
It's my project where I have integrated mega cloud storage. Thank you, everything works fine with your builded lib.
