### ISSUE TITLE
The string "Manage Chat History" is not translated.

### ISSUE THREAD

**Issue by wizard86pz** [meganz/iOS#55]
## General Information
The string "Manage Chat History" is not translated. Path: chat section, press on an existing chat, press on the contact name on top. The whole "Manage Chat History" section is not translated, expect for "Clear the chat" red command.

* MEGA Version:
5.9.4 (21031714)
MEGA DSK b0b4fc511
SDK MEGAchat 698d5fc4

* iOS Version(s):
14.4.1 (18D61).

* Devices/Simulators:
iPhone X.

* Reproducible? (Yes/No):
Yes (always).

##  What happened?
No translations.

## What did you expect to happen?
Strings translated.

![image](https://user-images.githubusercontent.com/36189429/111518695-9adc5400-8756-11eb-8acd-6c7ba9751926.png)

![image](https://user-images.githubusercontent.com/36189429/111518738-a62f7f80-8756-11eb-9f1f-b249c0ce9681.png)

**Comment by javisanesp** [comment]
Hello @wizard86pz,

Thank you for reporting. It should be translated on the next version. Same for the footers on the 'Manage Chat History' view. 

Cheers!
