### ISSUE TITLE
Amount of space not updated if the trash can is cleaned

### ISSUE THREAD

**Issue by wizard86pz** [meganz/iOS#57]
## General Information

* MEGA Version: 5.12.2. (21042137)

* iOS Version(s): 14.5.1 (18E212)

* Devices/Simulators: iPhone 12

* Reproducible? (Yes/No): Yes

##  What happened?
Every time I simply clean the trash can of my cloud, the app seems to not do anything. I need to go back and check if the trash can has been correctly cleaned up.

Note: this happens ONLY if I perform a cleaning from: app settings, file management, trash can, empty the trash can.

## What did you expect to happen?
Once I perform the cleaning, the amount of space used by the trash can, is updated to "0 B". Exactly how it works if I decide to remove all the previous versions of my files in the cloud.

**Comment by sakethv-mega** [comment]
Hello there, thank you for reporting. We were able to reproduce the issue and it has been raised to developers for a fix.

**Comment by wizard86pz** [comment]
Thanks @sakethv-mega. BTW in last TF beta (5.13 21050796) is still occurring.

**Comment by wizard86pz** [comment]
Thanks, it has been fixed in last TestFlight beta.
