### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by wizard86pz** [meganz/iOS#59]
## General Information

* MEGA Version: 5.14 (21051852)

* iOS Version(s): 14.5.1

* Devices/Simulators: iPhone 12

* Reproducible? (Yes/No): Yes

##  What happened?
The following maing settings strings are not translated:
- "Camera Uploads"
- "Security" and its sub-menu string "QR Code"
- "Terms and Policies" and its sub-menu string "Privacy Policy"

## What did you expect to happen?
I expect to see those strings translated in iOS device language.

**Comment by jnavarrom** [comment]
Hi @wizard86pz , what is the language of the device?

"Security" and "Terms and Policies" are not translated yet, they appear only in English.

The others string are translated to other languages, but not to all: see the attached screenshots
<img width="735" alt="Screenshot 2021-05-20 at 11 13 09" src="https://user-images.githubusercontent.com/3861964/118953182-e11f8080-b95c-11eb-8336-9ceb0d197954.png">
<img width="735" alt="Screenshot 2021-05-20 at 11 15 17" src="https://user-images.githubusercontent.com/3861964/118953195-e41a7100-b95c-11eb-8233-fea93d1ec79f.png">
<img width="738" alt="Screenshot 2021-05-20 at 11 14 53" src="https://user-images.githubusercontent.com/3861964/118953198-e54b9e00-b95c-11eb-844d-f9d32f213d20.png">
<img width="735" alt="Screenshot 2021-05-20 at 11 13 35" src="https://user-images.githubusercontent.com/3861964/118953200-e5e43480-b95c-11eb-8f3e-6544899a9a80.png">
<img width="720" alt="Screenshot 2021-05-20 at 11 17 37" src="https://user-images.githubusercontent.com/3861964/118953321-00b6a900-b95d-11eb-9c5f-43823d57b05c.png">

**Comment by wizard86pz** [comment]
Hi, thanks for the reply. I've tested for italian language.

**Comment by jnavarrom** [comment]
None of the strings you have reported are translated into Italian. I will contact our Italian translator.
Thanks

**Comment by wizard86pz** [comment]
Thanks, do you have a publicly accessible translations platform to use to suggest/check translated strings?

**Comment by jnavarrom** [comment]
No, we use private platform to deal with translations.

But if you want you can check the translations in this repository. Italian strings are here: https://github.com/meganz/iOS/tree/master/iMEGA/Languages/it.lproj

**Comment by wizard86pz** [comment]
Thanks!
