### ISSUE TITLE
JavaScript not working help fix 

### ISSUE THREAD

**Issue by Matt1242** [meganz/iOS#63]
## General Information

* MEGA Version:

* iOS Version(s):

* Devices/Simulators:

* Reproducible? (Yes/No):

Yes
##  What happened?

Tried to open a html file and it said to enable JavaScript to continue 

## What did you expect to happen?
It to open no problem

**Comment by jnavarrom** [comment]
Hello,

Need more information or if you can share a HTML file that causes the problem would be great.

https://user-images.githubusercontent.com/3861964/123117504-162e5f80-d442-11eb-9a0c-fca79d4f202d.MP4

Thanks
