### ISSUE TITLE
Feature suggestion : Choose multiple files to upload

### ISSUE THREAD

**Issue by awidesky** [meganz/iOS#64]
When we choose file to upload to mega via app, I hope we could upload multiple files at a time.
(Just like we choose multiple files to move or copy in iOS ```file``` app)

**Comment by angelds-mega** [comment]
Thanks for reaching us, we really appreciate your feedback! We are always trying to improve our product to provide you with a better experience. We will be sure to pass your suggestion onto our team for their consideration. 
Thank you.

**Comment by jnavarrom** [comment]
Hi it is possible select multiple files from Files:

https://user-images.githubusercontent.com/3861964/170502456-6c9bc13a-3110-4074-903c-ff863ba94c2e.MP4
