### ISSUE TITLE
Maximize audio player plays the first selects song after a few songs again

### ISSUE THREAD

**Issue by loko789** [meganz/iOS#67]
## General Information

* MEGA Version:
7.2 (2202042222)
* iOS Version(s):
 15.2.1
* Devices/Simulators:

* Reproducible? (Yes/No):
Yes

##  What happened?

- Choose offline content
- Select any song
- Minimize music player
- Swipe some song further (it doesn't matter if you swipe or if you play the song to the end or how many songs further)
- Click on the music player to maximize it
- The player plays the song you selected first

My english ist not the best and not entirely understandable but i record it for better clarification. I hope I explained it clearly.

https://user-images.githubusercontent.com/32632188/153171865-35b06fca-b57f-42db-83fe-de44780c89ad.mov

## What did you expect to happen?
Play the current song when you maximize the player

_Powered by Google translate_ ;)

**Comment by angelds-mega** [comment]
Hello, this issue has already been reported and it will be fixed in our next release - version 7.4. Thank you.
