### ISSUE TITLE
App crash pressing on the 3 dots in the list of share element links

### ISSUE THREAD

**Issue by wizard86pz** [meganz/iOS#72]
## General Information
As in the title.

STR:
1. go to shared elements section
2. go to "link" tab
3. press on the 3 dots to manage the shared element link.

* MEGA Version: 7.9 (2205100530)

* iOS Version(s): 15.4.1 (19E258)

* Devices/Simulators: iPhone 12

* Reproducible? (Yes/No): Yes, all the times.

##  What happened?

The app crashes all the times the STR are executed.

## What did you expect to happen?

To manage the shared element link.

**Comment by jnavarrom** [comment]
Thanks for reporting, we will create a new version 7.9.1 and fix this crash.

**Comment by wizard86pz** [comment]
Great, thanks.

**Comment by wizard86pz** [comment]
Fixed in 7.9.1 (2205131332).
