### ISSUE TITLE
I want to do other work in picture-in-picture mode

### ISSUE THREAD

**Issue by kirasoga** [meganz/iOS#75]
## General Information

* MEGA Version:
latest
* iOS Version(s):
latest
* Devices/Simulators:
iPhone 12 pro max
* Reproducible? (Yes/No):
:)

##  What happened?
I want to do other work in picture-in-picture mode.

~/Offline/OfflineViewController

756
-                            [self presentViewController:megaAVViewController animated:YES completion:nil];
+                            [self.navigationController presentViewController:megaAVViewController animated:YES completion:nil];

What if you make a transition with navigation?

## What did you expect to happen?
I thought I could see other images while watching the video

im japanese,
I'm sorry if it doesn't get through

**Comment by jx-mega** [comment]
Hi, can you please explain to us the steps performed and send us a screenshot of the error if possible?
Please email us the details to support@mega.nz from your MEGA account email address and we will be happy to help you.

**Comment by kirasoga** [comment]
sorry.
