### ISSUE TITLE
Feature request: allow mobile apps (Android and iOS) to create "File request"

### ISSUE THREAD

**Issue by wizard86pz** [meganz/iOS#80]
## General Information

* MEGA Version:

* iOS Version(s):

* Devices/Simulators:

* Reproducible? (Yes/No):

**Comment by vbs-mega** [comment]
Hello,

Thank you very much for your suggestion. We have now passed it on to our developers for consideration.

Have a MEGA-awesome day and contact us should you need any other assistance.

We appreciate all feedback and are working to improve and integrate new features with this feedback in mind.
