### ISSUE TITLE
Feature request: Automatic background camera roll uploads

### ISSUE THREAD

**Issue by Wrestor** [meganz/iOS#97]
Automatically upload all new photos and videos in the background. Currently one is forced to open the mega app once in a while because if you don't, every image and video taken since one has last opened it, won't be uploaded to mega. Even if the app is in the launcher (not forced closed). This is cumbersome.

Edit: Also, on the App Store, it says "Automatic Synchronisation of photos and videos". If I need to undertake a manual action for it to happen, it's not truly automatic. This is misleading.

<img src="https://github.com/meganz/iOS/assets/54822494/73405312-ee1d-4917-8d9e-075e9d1c6e1e" width=25% height=25%>

**Comment by jx-mega** [comment]
Hello,
If you are still facing this issue, please contact us at support@mega.nz from your account email address so we can check it from there.
